sudo: false
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean package
after_script:
- mvn generate-resources -Pdocs -Dmaven.test.skip=true
- mvn -q scm-publish:publish-scm -Pdocs -Dmaven.test.skip=true
env:
  global:
    secure: LrR0J5QFBSsyap3zvo4sU/sAJqwBcHKQTvzcWiA2ayQVEMO8C3chFCq6W9J5tSX91mVNt+h2A0QBXoIxv98w7CiXWfmf0fvGLLuGqy8zMPAp+/RZ5t5oEkHuZGQRV7CS/F9bv3rnrQZkBAYJS4eigrjoMq4GhQ1TiqFcc83Xztmij81cCec6FC01aMzVcppD0bvgVFTOU0wjeqWxIby4bHesT2td5BMBsI8JtXtLync2V/e472Of/dkhwxhI43B3G5bTLy5DPpITKd185vzJedFgrQ3PDjV9tSwi1D3sPwRbCfMq31+IEHA9Vg8gE7nn9CNQ9SIVzfIYZcwvc6WNkOE/bslkVpW2XUxTl3Tonk/okHTRiyjZFJpOL3gQ0Uq6W9+AWAh1VYeJR7N4RO5D8+Ecfm/PnGvdRSX8UUOTYoRXS0bvLS+Zxjpk1uC9jpD/Ae1svLoZVBIuWJYR9ic/u/pQk771xU2g2ZKnzpDYBApK8ckB1TeWR8DDJlzLuvkLOFcS3nPEtZl6+SrMvMKaNRPNrN2zY8EQ28Qa4/Ypo6Ed+Uub9qxx/IJtSzaYzM/DcCOh74n9sENzcANDWmM4CUM2syfLNMo2NKnDoGHYSxBnLKcgD4nqJgTAHCNGbqjtr5LyfK9DG0ZrAwmmjIw9eFmT18RXNiABC9t3Vzanzdo=
